[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
broker = { path = "../broker" }
contract = { path = "../contract" }
uuid = { version = "1.10.0", features = ["v4", "js"] }
